spring.application.name=barriocircular
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://...
spring.datasource.username=postgres.......
spring.datasource.password=password...
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
clerk.jwks-uri=https://communal..../jwks.json
clerk.issuer=https://communal.....accounts.dev